version: '3.8'

services:
  cinerent_hub_app:
    build: .
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app
    ports:
      - "${APP_PORT}:3000"
    depends_on:
      - cinerent_hub_mongo
    environment:
      - NODE_ENV=${NODE_ENV}
      - APP_PORT=${APP_PORT}
      - MONGO_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_SERVICE_NAME=${MONGO_SERVICE_NAME}
      - MONGO_PORT=${MONGO_PORT}
      - DATABASE=${MONGO_DATABASE}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - cinerent_hub_network

  cinerent_hub_mongo:
    build:
      context: .
      dockerfile: Dockerfile.mongodb
    volumes:
      - mongodb_data:/data/db
      - ./mongo-seed:/docker-entrypoint-initdb.d
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
    networks:
      - cinerent_hub_network

  mongo-express:
    image: mongo-express:latest
    depends_on:
      - cinerent_hub_mongo
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: cinerent_hub_mongo
    networks:
      - cinerent_hub_network

networks:
  cinerent_hub_network:
    driver: bridge

volumes:
  mongodb_data:
